# cloudformation solution goes here

AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template that does Anomaly Detection

Parameters: 
  InstanceType: 
    Description: The EC2 instance type
    Type: String
    Default: t3.micro
    AllowedValues: 
      - t3.micro
      - t3.small 
      - t3.medium
  KeyName: 
    Description: Name of an existing EC2 key pair to allow SSH access to the instances
    Type: 'AWS::EC2::KeyPair::KeyName'
  UvaId:
    Description: UVA computing ID
    Type: String
    MinLength: 3
    MaxLength: 9
  MyIP: 
    Description: THE CURRENT IP LOCATION... 
    Type: String
    MinLength: 9
    MaxLength: 20
    Default: 0.0.0.0/0
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.



Resources:
  # EC2 Instance
  AppInstance:
    Type: AWS::EC2::Instance
    DependsOn: SNSTopicPolicy
    Properties:
      ImageId: ami-04b70fa74e45c3917 # Ubuntu 20.04 for us-east-1
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref IAMInstanceProfile
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 16 # 16 GB
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e


          # Bootstrapping script
          apt-get update -y
          apt-get install -y git python3 python3-pip python3-venv git

          # set up Bucket Name
          export BUCKET_NAME="${S3Bucket}"
          echo "BUCKET_NAME='${S3Bucket}'" >> /etc/environment



          # Clone repository and setup env
          cd /home/ubuntu
          git clone https://github.com/oof6/anomaly-detection.git app
          cd app

          # create virtual environment
          python3 -m venv venv
          source venv/bin/activate


          
          # install requirements
          pip install -r requirements.txt
          pip install fastapi uvicorn

          # run the application
          mkdir -p logs
          chown -R ubuntu:ubuntu /home/ubuntu/app
          sudo -u ubuntu BUCKET_NAME='${S3Bucket}' bash -c "source /home/ubuntu/app/venv/bin/activate && fastapi run app.py --port 8000" &

        
      # Tags:
      #   - Key: Name
      #     Value: !Sub ${AWS::StackName}-ec2-instance
      

  

  # Security Group

# Security Group allowing ports 80 and 22
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2 instance allowing HTTP and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0
          Description: Allow HTTP traffic from anywhere
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP
          Description: Allow SSH access from my IP
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ec2-sg


  
  # Elastic IP
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref AppInstance
      


  # S3 Bucket
  S3Bucket:
    Type: AWS::S3::Bucket
    DependsOn: SNSTopicPolicy
    Properties:
      BucketName: !Sub ${UvaId}-${AWS::StackName}
      # S3 event notification 
      NotificationConfiguration:
        TopicConfigurations: 
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: raw/
                  - Name: suffix
                    Value: .csv
            Topic: !Ref SNSTopic
      # ********************
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-s3-bucket

  # IAM Role and Policy
  IAMInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: 
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
  # policies
  IAMInstancePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3BucketAccessPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !Sub ${S3Bucket.Arn}/*
              - !Sub ${S3Bucket.Arn}
      Roles:
        - !Ref IAMInstanceRole
  # profile
  IAMInstanceProfile:
     Type: AWS::IAM::InstanceProfile
     Properties:
       Roles:
         - !Ref IAMInstanceRole   

  # SNS Topic and Subscription
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ds5220-dp1
  
  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: 
              Service: s3.amazonaws.com
            Action: SNS:Publish
            Resource: !Ref SNSTopic 
            Condition:
              ArnLike:
                aws:SourceArn: !Sub arn:aws:s3:::${UvaId}-${AWS::StackName}
      Topics:
        - !Ref SNSTopic


  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: http
      # uses the endpoint of the Elastic IP
      Endpoint: !Sub http://${ElasticIP}:8000/notify
      TopicArn: !Ref SNSTopic




Outputs:
  InstancePublicIP:
    Description: Public IP address of the instance
    Value: !Ref ElasticIP

  S3BucketName:
    Description: The name of the S3 bucket
    Value: !Ref S3Bucket
